apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        app3: web
    spec:
      containers:
      - name: apache
        image: httpd:2.4-alpine
        volumeMounts:
        - name: volume1
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: volume1
        hostPath: 
          path: /web
          type: DirectoryOrCreate